openapi: 3.0.2
info:
  version: '1.1'
  title: Open API for FSP Interoperability (FSPIOP)
  description: >-
    Based on [API Definition updated on 2020-05-19 Version
    1.1](https://github.com/mojaloop/mojaloop-specification/blob/master/documents/v1.1-document-set/API%20Definition_v1.1.pdf).


    **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in
    the HTTP header.
  license:
    name: CC BY-ND 4.0
    url: 'https://github.com/mojaloop/mojaloop-specification/blob/master/LICENSE.md'
  contact:
    name: Sam Kummary
    url: 'https://github.com/mojaloop/mojaloop-specification/issues'
servers:
  - url: 'protocol://hostname:<port>/switch/'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
paths:
  /participants/Type/ID:
    $ref: 'paths/participants_Type_ID.yaml'
  /participants/Type/ID/error:
    $ref: 'paths/participants_Type_ID_error.yaml'
  /participants/Type/ID/SubId:
    $ref: 'paths/participants_Type_ID_SubId.yaml'
  /participants/Type/ID/SubId/error:
    $ref: 'paths/participants_Type_ID_SubId_error.yaml'
  /participants:
    $ref: 'paths/participants.yaml'
  /participants/ID:
    $ref: 'paths/participants_ID.yaml'
  /participants/ID/error:
    $ref: 'paths/participants_ID_error.yaml'
  /parties/Type/ID:
    $ref: 'paths/parties_Type_ID.yaml'
  /parties/Type/ID/error:
    $ref: 'paths/parties_Type_ID_error.yaml'
  /parties/Type/ID/SubId:
    $ref: 'paths/parties_Type_ID_SubId.yaml'
  /parties/Type/ID/SubId/error:
    $ref: 'paths/parties_Type_ID_SubId_error.yaml'
  /transactionRequests:
    $ref: 'paths/transactionRequests.yaml'
  /transactionRequests/ID:
    $ref: 'paths/transactionRequests_ID.yaml'
  /transactionRequests/ID/error:
    $ref: 'paths/transactionRequests_ID_error.yaml'
  /quotes:
    $ref: 'paths/quotes.yaml'
  /quotes/ID:
    $ref: 'paths/quotes_ID.yaml'
  /quotes/ID/error:
    $ref: 'paths/quotes_ID_error.yaml'
  /authorizations/ID:
    $ref: 'paths/authorizations_ID.yaml'
  /authorizations/ID/error:
    $ref: 'paths/authorizations_ID_error.yaml'
  /transfers:
    $ref: 'paths/transfers.yaml'
  /transfers/ID:
    $ref: 'paths/transfers_ID.yaml'
  /transfers/ID/error:
    $ref: 'paths/transfers_ID_error.yaml'
  /transactions/ID:
    $ref: 'paths/transactions_ID.yaml'
  /transactions/ID/error:
    $ref: 'paths/transactions_ID_error.yaml'
  /bulkQuotes:
    $ref: 'paths/bulkQuotes.yaml'
  /bulkQuotes/ID:
    $ref: 'paths/bulkQuotes_ID.yaml'
  /bulkQuotes/ID/error:
    $ref: 'paths/bulkQuotes_ID_error.yaml'
  /bulkTransfers:
    $ref: 'paths/bulkTransfers.yaml'
  /bulkTransfers/ID:
    $ref: 'paths/bulkTransfers_ID.yaml'
  /bulkTransfers/ID/error:
    $ref: 'paths/bulkTransfers_ID_error.yaml'
